### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by andrewfer000** [fastogt/fastocloud#12]
So I found this software while trying to learn about streaming technology and this neat program caught my eye.

I just wanted to know
1. Can I install this along with my pre existing website? (I use Apache)
2. What ports does this software use and can I easily change them?
3. Chan I use OBS (Open Broadcast Software) Studio to run a live channel?
4. Can users just use their web browsers + mobile device to stream?
5. Can I set it so no login is required?
6. Can I set the admin panel up to use a reverse proxy (i.e admin.mysite.com)

Thank you and I hope to be able to check out your software!

**Comment by andrewfer000** [comment]
With the OBS thing I want to be able to take my live desktop feed and send it to the server so online users can watch it or any input device I set. Can I also have it so I can have pre-recorded content play when I'm not there?

**Comment by topilski** [comment]
Hey @andrewfer000 , so my answers are next:
1) Yes, you can install on your website but you need to forward-proxy port on services (from Apache, Nginx) no matter.
2) You can find the port in config files, for panel and services all ports you can change.
3) Yes, you can use, and this stream you can convert or relay or what do you want.
4) Yes, players come to services receive channels and start playing, all rebranding and additional functionality we can do by our team.
5) Yes, by request, if you will be our client we will hide login activity, now Android/iPhone in private repositories, available only for our paid clients.
6) Yes, it PROXY streams do what you want.

Yes, we can brand players according to your specs (change resources, design, add new specific features), lifestreams, recorded no matter our service works with different inputs.

**Comment by andrewfer000** [comment]
Well im not here as a customer im here as a researcher. I need a way to be able to have "users" view a multi-channel live stream(s) from all devices (universally using a web browser on the website)

**Comment by topilski** [comment]
We also have web-players in private repos.

**Comment by andrewfer000** [comment]
Will you make them public? Because this project is starting to feel like some open source freenium software like MistServer. I was hoping this would be a fully featured  GPL licenced project. Well cya I guess

**Comment by topilski** [comment]
And how I should pay for my developers? Players, it is our internal development, it is not a GPL license. GPL license only for GStreamer/Qt/FFmpeg based projects, other sources we can hide it is our choice.

**Comment by andrewfer000** [comment]
I was thinking that this was a community project since you did not have a lot of information regarding sales or premium features on your site. I know that devs have to be paid i'm one myself. I honestly thought this was a corporate sponsored / community project

**Comment by topilski** [comment]
You can learn how FastoTV player connect to IPTV service here protocol: https://github.com/fastogt/fastotv/wiki/API
