### ISSUE TITLE
Installed on latest Ubuntu Server, getting this error: gst_element_factory_make no such element factory "openh264enc"!

### ISSUE THREAD

**Issue by DanielQuirogaDev** [fastogt/fastocloud#18]
daniel@encoder:/home/fastocloud/streamer/feedback/2/5d9ebb3941649652fef56641$ cat logs 
05:01:51.450 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:01:51.466 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:01:51.466 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:01:51.466 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(50)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:01:52.864 streamer_5d9ebb3941649652fef56641 [DEBUG] Generated url: http://172.16.20.2:8081/sangil320/caracoltv/chunks.m3u8?nimblesessionid=24172
05:01:52.864 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:01:52.871 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/chunks.m3u8?nimblesessionid=24172
05:01:52.871 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:01:52.877 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "openh264enc"!
05:01:52.877 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'openh264enc' named: video_codec_0
05:02:42.193 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:02:42.209 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:02:42.209 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:02:42.209 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(53)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:02:43.578 streamer_5d9ebb3941649652fef56641 [DEBUG] Generated url: http://172.16.20.2:8081/sangil320/caracoltv/chunks.m3u8?nimblesessionid=24173
05:02:43.578 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:02:43.585 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/chunks.m3u8?nimblesessionid=24173
05:02:43.585 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:02:43.591 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "openh264enc"!
05:02:43.591 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'openh264enc' named: video_codec_0
05:03:34.803 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:03:34.818 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:03:34.818 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:03:34.818 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(56)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:03:34.819 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:03:34.824 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:03:34.824 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:03:34.830 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "openh264enc"!
05:03:34.830 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'openh264enc' named: video_codec_0
05:06:16.952 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:06:16.968 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:06:16.968 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:06:16.968 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(59)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:06:16.968 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:06:16.975 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:06:16.975 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:06:16.981 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "openh264enc"!
05:06:16.981 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'openh264enc' named: video_codec_0
05:06:18.230 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:06:18.245 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:06:18.245 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:06:18.245 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(62)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:06:18.245 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:06:18.252 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:06:18.252 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:06:18.258 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "openh264enc"!
05:06:18.258 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'openh264enc' named: video_codec_0
05:06:43.649 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:06:43.664 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:06:43.664 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:06:43.665 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(65)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:06:43.665 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:06:43.672 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:06:43.672 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:06:43.683 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "h264parse"!
05:06:43.683 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'h264parse' named: video_parser_0
05:07:05.530 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:07:05.545 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:07:05.545 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:07:05.545 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(68)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:07:05.545 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:07:05.552 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:07:05.552 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:07:05.561 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "h264parse"!
05:07:05.561 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'h264parse' named: video_parser_0
05:07:06.682 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:07:06.695 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:07:06.695 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:07:06.695 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(71)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:07:06.695 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:07:06.700 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:07:06.700 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:07:06.708 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "h264parse"!
05:07:06.708 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'h264parse' named: video_parser_0
05:07:23.177 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:07:23.192 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:07:23.192 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:07:23.192 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(74)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:07:23.192 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:07:23.199 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:07:23.199 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:07:23.204 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "eavcenc"!
05:07:23.204 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'eavcenc' named: video_codec_0
05:07:54.408 streamer_5d9ebb3941649652fef56641 [NOTICE] Running 1.6.2.0 Revision: df32ec5
05:07:54.424 streamer_5d9ebb3941649652fef56641 [DEBUG] Stream backend inited, LIBVA_DRIVER_NAME=(null), LIBVA_DRIVERS_PATH=(null)
05:07:54.424 streamer_5d9ebb3941649652fef56641 [INFO] Child listening started!
05:07:54.424 streamer_5d9ebb3941649652fef56641 [INFO] Successfully connected with client[[5d9ebb3941649652fef56641][PipeClient(77)]], from server[[main][StreamServer(8)]], 1 client(s) connected.
05:07:54.424 streamer_5d9ebb3941649652fef56641 [INFO] Changing status to: New
05:07:54.430 streamer_5d9ebb3941649652fef56641 [DEBUG] InputPad created id: 0, url: http://172.16.20.2:8081/sangil320/caracoltv/playlist.m3u8
05:07:54.430 streamer_5d9ebb3941649652fef56641 [DEBUG] Input probe added id: 1
05:07:54.436 streamer_5d9ebb3941649652fef56641 [WARNING] GST_ELEMENT_FACTORY ../gst/gstelementfactory.c:456 gst_element_factory_make no such element factory "eavcenc"!
05:07:54.436 streamer_5d9ebb3941649652fef56641 [CRITICAL] Cannot create 'eavcenc' named: video_codec_0

**Comment by topilski** [comment]
Hey, did you build openh264enc plugin?

**Comment by DanielQuirogaDev** [comment]
Well, i followed the instructions on the wiki, but i didn't see how to build it. Sorry man. 

Can provide some input in how? Please? (Awesome product, feels very complete and stable)

**Comment by topilski** [comment]
We don't build all gstreamer plugins, we build only needed. https://github.com/fastogt/fastocloud/blob/master/build/build_env.py#L268 You need to build openh264enc as we did for faac for example.

**Comment by DanielQuirogaDev** [comment]
Which ones are needed, what codec would work out of the box for h264?

**Comment by topilski** [comment]
x264

**Comment by DanielQuirogaDev** [comment]
Tought so, but it failed with same error msg.

**Comment by DanielQuirogaDev** [comment]
I am rebuilding everything to see if i made a mistake (which is very likely)

**Comment by DanielQuirogaDev** [comment]
Check plugin decodebin, success return code: 0
Check plugin fakesink, success return code: 0
Check plugin testsink, success return code: 0
Check plugin videotestsrc, success return code: 0
Check plugin audiotestsrc, success return code: 0
Check plugin autovideosink, success return code: 0
Check plugin autoaudiosink, success return code: 0
Check plugin queue, success return code: 0
Check plugin queue2, success return code: 0
Check plugin h264parse, failed return code: 255
Check plugin h265parse, failed return code: 255
Check plugin mpegvideoparse, failed return code: 255
Check plugin aacparse, success return code: 0
Check plugin ac3parse, success return code: 0
Check plugin mpegaudioparse, success return code: 0
Check plugin rawaudioparse, success return code: 0
Check plugin tee, success return code: 0
Check plugin flvmux, success return code: 0
Check plugin mpegtsmux, failed return code: 255
Check plugin filesink, success return code: 0
Check plugin rtpmux, success return code: 0
Check plugin rtpmp2tpay, success return code: 0
Check plugin rtph264pay, success return code: 0
Check plugin rtph265pay, success return code: 0
Check plugin rtpmp4apay, success return code: 0
Check plugin rtpac3pay, success return code: 0
Check plugin rtpmp2tdepay, success return code: 0
Check plugin rtph264depay, success return code: 0
Check plugin rtph265depay, success return code: 0
Check plugin rtpmp4adepay, success return code: 0
Check plugin rtpac3depay, success return code: 0
Check plugin v4l2src, success return code: 0
Check plugin splitmuxsink, success return code: 0
Check plugin alsasrc, success return code: 0
Check plugin multifilesrc, success return code: 0
Check plugin appsrc, success return code: 0
Check plugin filesrc, success return code: 0
Check plugin imagefreeze, success return code: 0
Check plugin capsfilter, success return code: 0
Check plugin audioconvert, success return code: 0
Check plugin rgvolume, success return code: 0
Check plugin volume, success return code: 0
Check plugin faac, failed return code: 255
Check plugin voaacenc, failed return code: 255
Check plugin audioresample, success return code: 0
Check plugin lamemp3enc, success return code: 0
Check plugin videoconvert, success return code: 0
Check plugin avdeinterlace, success return code: 0
Check plugin deinterlace, success return code: 0
Check plugin aspectratiocrop, success return code: 0
Check plugin udpsink, success return code: 0
Check plugin tcpserversink, success return code: 0
Check plugin rtmpsink, failed return code: 255
Check plugin hlssink, failed return code: 255
Check plugin souphttpsrc, success return code: 0
Check plugin videoscale, success return code: 0
Check plugin videorate, success return code: 0
Check plugin multifilesink, success return code: 0
Check plugin nvh264enc, failed return code: 255
Check plugin msdkh264enc, failed return code: 255
Check plugin x264enc, success return code: 0
Check plugin x265enc, failed return code: 255
Check plugin mpeg2enc, failed return code: 255
Check plugin eavcenc, failed return code: 255
Check plugin openh264enc, failed return code: 255
Check plugin udpsrc, success return code: 0
Check plugin rtmpsrc, failed return code: 255
Check plugin rtspsrc, success return code: 0
Check plugin tcpserversrc, success return code: 0
Check plugin vaapih264enc, failed return code: 255
Check plugin vaapimpeg2enc, failed return code: 255
Check plugin vaapidecodebin, failed return code: 255
Check plugin vaapipostproc, failed return code: 255
Check plugin gdkpixbufoverlay, success return code: 0
Check plugin videobox, success return code: 0
Check plugin videomixer, success return code: 0
Check plugin audiomixer, success return code: 0
Check plugin interleave, success return code: 0
Check plugin deinterleave, success return code: 0
Check plugin cairooverlay, success return code: 0
Check plugin videocrop, success return code: 0
Check plugin spectrum, success return code: 0
Check plugin level, success return code: 0
Check plugin hlsdemux, failed return code: 255
Check plugin decklinkvideosink, failed return code: 255
Check plugin decklinkaudiosink, failed return code: 255
Check plugin interlace, failed return code: 255
Check plugin autovideoconvert, failed return code: 255
Check plugin tsparse, failed return code: 255
Check plugin avdec_h264, success return code: 0
Check plugin tsdemux, failed return code: 255
Check plugin avdec_ac3, success return code: 0
Check plugin avdec_ac3_fixed, success return code: 0
Check plugin avdec_aac, success return code: 0
Check plugin avdec_aac_fixed, success return code: 0
Check plugin souphttpclientsink, success return code: 0
Check plugin mfxh264enc, failed return code: 255
Check plugin mfxvpp, failed return code: 255
Check plugin mfxh264dec, failed return code: 255
Check plugin tinyyolov2, failed return code: 255
Check plugin tinyyolov3, failed return code: 255
Check plugin detectionoverlay, failed return code: 255
Check plugin kvssink, failed return code: 255

**Comment by Saentist** [comment]
I have same errors using clear fresh instaled Ubuntu 18.04 x64.

**Comment by topilski** [comment]
it is ok, we not setup openh264 in build_env.py script

**Comment by DanielQuirogaDev** [comment]
> > it is ok, we not setup openh264 in build_env.py script
> 
> So what need to be done to fix this issue?
> 
> ```
> Check plugin decodebin, success return code: 0
> Check plugin fakesink, success return code: 0
> Check plugin testsink, success return code: 0
> Check plugin videotestsrc, success return code: 0
> Check plugin audiotestsrc, success return code: 0
> Check plugin autovideosink, success return code: 0
> Check plugin autoaudiosink, success return code: 0
> Check plugin queue, success return code: 0
> Check plugin queue2, success return code: 0
> Check plugin h264parse, success return code: 0
> Check plugin h265parse, success return code: 0
> Check plugin mpegvideoparse, success return code: 0
> Check plugin aacparse, success return code: 0
> Check plugin ac3parse, success return code: 0
> Check plugin mpegaudioparse, success return code: 0
> Check plugin rawaudioparse, success return code: 0
> Check plugin tee, success return code: 0
> Check plugin flvmux, success return code: 0
> Check plugin mpegtsmux, success return code: 0
> Check plugin filesink, success return code: 0
> Check plugin rtpmux, success return code: 0
> Check plugin rtpmp2tpay, success return code: 0
> Check plugin rtph264pay, success return code: 0
> Check plugin rtph265pay, success return code: 0
> Check plugin rtpmp4apay, success return code: 0
> Check plugin rtpac3pay, success return code: 0
> Check plugin rtpmp2tdepay, success return code: 0
> Check plugin rtph264depay, success return code: 0
> Check plugin rtph265depay, success return code: 0
> Check plugin rtpmp4adepay, success return code: 0
> Check plugin rtpac3depay, success return code: 0
> Check plugin v4l2src, success return code: 0
> Check plugin splitmuxsink, success return code: 0
> Check plugin alsasrc, success return code: 0
> Check plugin multifilesrc, success return code: 0
> Check plugin appsrc, success return code: 0
> Check plugin filesrc, success return code: 0
> Check plugin imagefreeze, success return code: 0
> Check plugin capsfilter, success return code: 0
> Check plugin audioconvert, success return code: 0
> Check plugin rgvolume, success return code: 0
> Check plugin volume, success return code: 0
> Check plugin faac, success return code: 0
> Check plugin voaacenc, failed return code: 255
> Check plugin audioresample, success return code: 0
> Check plugin lamemp3enc, success return code: 0
> Check plugin videoconvert, success return code: 0
> Check plugin avdeinterlace, success return code: 0
> Check plugin deinterlace, success return code: 0
> Check plugin aspectratiocrop, success return code: 0
> Check plugin udpsink, success return code: 0
> Check plugin tcpserversink, success return code: 0
> Check plugin rtmpsink, success return code: 0
> Check plugin hlssink, success return code: 0
> Check plugin souphttpsrc, success return code: 0
> Check plugin videoscale, success return code: 0
> Check plugin videorate, success return code: 0
> Check plugin multifilesink, success return code: 0
> Check plugin nvh264enc, success return code: 0
> Check plugin msdkh264enc, failed return code: 255
> Check plugin x264enc, success return code: 0
> Check plugin x265enc, failed return code: 255
> Check plugin mpeg2enc, failed return code: 255
> Check plugin eavcenc, failed return code: 255
> Check plugin openh264enc, failed return code: 255
> Check plugin udpsrc, success return code: 0
> Check plugin rtmpsrc, success return code: 0
> Check plugin rtspsrc, success return code: 0
> Check plugin tcpserversrc, success return code: 0
> Check plugin vaapih264enc, failed return code: 255
> Check plugin vaapimpeg2enc, failed return code: 255
> Check plugin vaapidecodebin, failed return code: 255
> Check plugin vaapipostproc, failed return code: 255
> Check plugin gdkpixbufoverlay, success return code: 0
> Check plugin videobox, success return code: 0
> Check plugin videomixer, success return code: 0
> Check plugin audiomixer, success return code: 0
> Check plugin interleave, success return code: 0
> Check plugin deinterleave, success return code: 0
> Check plugin cairooverlay, success return code: 0
> Check plugin videocrop, success return code: 0
> Check plugin spectrum, success return code: 0
> Check plugin level, success return code: 0
> Check plugin hlsdemux, success return code: 0
> Check plugin decklinkvideosink, success return code: 0
> Check plugin decklinkaudiosink, success return code: 0
> Check plugin interlace, success return code: 0
> Check plugin autovideoconvert, success return code: 0
> Check plugin tsparse, success return code: 0
> Check plugin avdec_h264, success return code: 0
> Check plugin tsdemux, success return code: 0
> Check plugin avdec_ac3, success return code: 0
> Check plugin avdec_ac3_fixed, success return code: 0
> Check plugin avdec_aac, success return code: 0
> Check plugin avdec_aac_fixed, success return code: 0
> Check plugin souphttpclientsink, success return code: 0
> Check plugin mfxh264enc, failed return code: 255
> Check plugin mfxvpp, failed return code: 255
> Check plugin mfxh264dec, failed return code: 255
> Check plugin tinyyolov2, failed return code: 255
> Check plugin tinyyolov3, failed return code: 255
> Check plugin detectionoverlay, failed return code: 255
> Check plugin kvssink, failed return code: 255
> ```

It seems that the requirement list is broken, there is no way to build that plugin or nvenc's.

I had to buy nimble streamer while i figure how to use Fasto :(

**Comment by topilski** [comment]
All GPU transcoding available only for our customers.
