### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Ya-Ri** [fastogt/fastocloud#24]
Hi

can you provide a more explained step by step guide on how to...
And as i understand, there is a paid plan ongoing...
Not really an issue, but would appreciate that the product will be functionnal out of box(following your wiki)
As it is, no way to evaluate the solution, i waste much time with your docker image and compilation
If you would like translation in french, and writing of a technical article, something that i can manage once success with the install and satisfy with the evaluation

Kind Regards,

Yamar

**Comment by topilski** [comment]
Morning, here how to build https://github.com/fastogt/fastocloud/wiki/Build , docker compose work well for admin panel, panel in private repository
