### ISSUE TITLE
Docker exited (1)

### ISSUE THREAD

**Issue by Marthinius** [fastogt/fastocloud#25]
Hi, 
When the container is started, it immediately stops with an error Exited (1).
Log shows: standard_init_linux.go:211: _exec user process caused "exec format error"_

OS: Armbian
CPU: armv7

Commands: 
docker pull fastogt/fastocloud
docker run -d -p 6317:6317 image_id  [ **Exited (1) error**]

Thank you for this project

**Comment by topilski** [comment]
Hey, can you check how it works now? And docker for fastocloud_admin it is only UI you need to use docker-compose

**Comment by Marthinius** [comment]
I'll try it

pá 10. 1. 2020 v 9:43 odesílatel Alexandr Topilski <notifications@github.com>
napsal:

**Comment by topilski** [comment]
ping
