### ISSUE TITLE
Can't Get License Key

### ISSUE THREAD

**Issue by MapGuy11** [fastogt/fastocloud#27]
I just get this error

Traceback (most recent call last):
  File "/usr/local/bin/request_fastogt_license_key", line 4, in <module>
    __import__('pkg_resources').run_script('pyfastogt==1.0.0', 'request_fastogt_license_key')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/request_fastogt_license_key' not found in metadata at '/usr/local/lib/python3.6/dist-packages/pyfastogt-1.0.0.egg-info'

**Comment by topilski** [comment]
Intrested

**Comment by MapGuy11** [comment]
I tried with Docker did work but then the Web UI doesn't work

**Comment by topilski** [comment]
You can try reinstall pyfatogt

**Comment by MapGuy11** [comment]
Now getting:

request_license: error: argument --license_key: expected one argument

**Comment by topilski** [comment]
and? yes need --license_key argument
