### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by YaPaY** [fastogt/fastocloud#37]
-- Configuring incomplete, errors occurred!
See also "/root/fastocloud/build/fastocloud/build/build_linux/build_cmake_release/CMakeFiles/CMakeOutput.log".
See also "/root/fastocloud/build/fastocloud/build/build_linux/build_cmake_release/CMakeFiles/CMakeError.log".
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
root@server2:~/fastocloud/build/fastocloud/build# systemctl enable fastocloud
Failed to enable unit: Unit file fastocloud.service does not exist.

**Comment by topilski** [comment]
Hello, don't think that build_env finished without errors

**Comment by EmilioCorti** [comment]
Hello, I have the same problem. I have used the installer until last week without problem, but now I have this error in fastocloud and fastotv
