### ISSUE TITLE
docker run ?

### ISSUE THREAD

**Issue by Erkalos** [fastogt/fastocloud#8]
Hey,

What is the good command line to start the soft with docker ? 
: I've tried : docker run --name test -p 6317:6317 -p 5000:5000 -p 6000:6000 -p 7000:7000 -p 8000:8000  fastogt/iptv --daemon
It's not working and 0 logs :(

**Comment by topilski** [comment]
Hey i think you need simple start docker image.

**Comment by sonymantha21** [comment]
after i use docker run, and next step use command docker exec fastocloud license_gen --machine-id, and got bin/sh not found..
I use debian strech server...

**Comment by topilski** [comment]
Hey @sonymantha21, thank you i will check

**Comment by topilski** [comment]
@sonymantha21 fixed please check

**Comment by sonymantha21** [comment]
still same i use docker and says bin/sh (fastocloud) not found

**Comment by topilski** [comment]
You need to rebuild image

**Comment by sonymantha21** [comment]
how i fix this bro : _

> err 18:16:24.691 fastocloud [ERROR] Can't open pid file path:/var/run/fastocloud/fastocloud.pid

_

**Comment by topilski** [comment]
you can remove this file

**Comment by sonymantha21** [comment]
really, and the port configuration?? for my case can't read  data cpu, memory, network etc.. help please

**Comment by topilski** [comment]
How you can check this fields without admin?

**Comment by sonymantha21** [comment]
i had admin panel

**Comment by topilski** [comment]
What version?

**Comment by sonymantha21** [comment]
i dont know how check the version

**Comment by topilski** [comment]
app/public_config.py

**Comment by sonymantha21** [comment]
version': 1.4.0 my panel

**Comment by topilski** [comment]
It is an old version, not compatible with master.

**Comment by monotsc** [comment]
is the admin panel no longer available ?

**Comment by topilski** [comment]
Availible in private repo, 25$ subscription.

**Comment by topilski** [comment]
Now 30$, we will update prices every month, a lot of customers want to use our solution.
